package com.example.authenticationservice.model

import com.example.authenticationservice.parameters.CreateEventRequest
import java.time.LocalDate
import javax.persistence.*

@Entity
class Event
  (
        @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        val id: Long = 0, /* The id value will be generated by JPA */

        @JoinColumn(name = "user_id")
        val creatorEvent: Long,

        @Column(nullable = false)
        val name: String,

        @Column(nullable = false)
        val local: String,

        @Column(nullable = false)
        val eventDate: LocalDate,

        @Column(nullable = false)
        val durationHours : Int,

        @Column(nullable = false)
        val salary : Float
    ) {
        val confirmed = false

        constructor(
            createEventRequest: CreateEventRequest, fkUser: Long
        ) : this(
                creatorEvent = fkUser,
                name =  createEventRequest.name,
                local =  createEventRequest.local,
                eventDate =  createEventRequest.eventDate,
                durationHours =  createEventRequest.durationHours,
                salary =  createEventRequest.salary
        )
    }
