package com.example.authenticationservice.model

import com.example.authenticationservice.dto.TypeUserDto
import com.example.authenticationservice.parameters.RegisterMusicianRequest
import java.time.LocalDate
import javax.persistence.*

@Entity
data class Musician(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long = 0, /* The id value will be generated by JPA */

    @JoinColumn (name = "user_id")
    val fkUser:Long,

    @Column(nullable = false)
    val description: String,

    @Column(nullable = false)
    val cep: String

){
    constructor() : this(

        fkUser = 0,
        description = "",
        cep = ""

    )

    constructor(registerMusicianRequest: RegisterMusicianRequest, fkUser: Long) : this(

        fkUser = fkUser,
        description = registerMusicianRequest.description,
        cep = registerMusicianRequest.cep
    )
}