package com.example.authenticationservice.model

import com.example.authenticationservice.parameters.CreateEventRequest
import java.time.LocalDate
import javax.persistence.*

@Entity
class MusicianInstrument
    (
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long = 0, /* The id value will be generated by JPA */

    @ManyToOne(fetch = FetchType.LAZY, targetEntity = Musician::class)
    @JoinColumn(name = "musician_id")
    val fkMusician: Long,
    @ManyToOne(fetch = FetchType.LAZY, targetEntity = Instrument::class)
    @JoinColumn(name = "instrument_id")
    val fkInstrument: Long
) {
}